<!DOCTYPE html>
<head>
    <title>Game Critique</title>
    <link rel="stylesheet" type="text/css" href="CSS/main.css" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

</head>
<body>
<div class ="wrapper">
<header>
    <h1><a href="?action=">Game Critique</a></h1>
    <p>Review your games here.</p>
    <nav>
        <ul>
            <li><a href="?action=">HOME</a></li>
            <li><a href="?action=login">LOGIN</a></li>
        </ul>
    </nav>

</header>
